---
- name: Copy files to Windows Server
  hosts: windows
  gather_facts: false
  vars:
    backup_file: "{{ lookup('pipe','date +%Y-%m-%d') }}"
    social_path: "C:\\Brokeree\\Brokeree.Social"
    api_path: "C:\\Brokeree\\Brokeree.Social\\API"
    ratings_path: "C:\\Brokeree\\Brokeree.Social\\Ratings"
    worker_path: "C:\\Brokeree\\Brokeree.Social\\Worker"
  tasks:
    - name: Create backup directories
      ansible.windows.win_file:
        path: C:\Brokeree\Brokeree.Social\_backup\{{ backup_file }}\{{ item.social_file }}
        state: directory
      loop:
        - { social_file: "API" }
        - { social_file: "Ratings" }
        - { social_file: "Worker" }

    - name: Copy Social API files - Coping
      ansible.windows.win_copy:
        src: "{ api_path }\\{{ item.source_file }}"
        dest: "{ social_path }\\_backup\\{{ backup_file }}\\API"
        remote_src: true
        when: API_file_data.stat.exists
      loop:
        - { source_file: 'templates', backup_file: '' }
        - { source_file: 'ijwhost.dll', backup_file: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', backup_file: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', backup_file: 'MNLog.config' }
        - { source_file: 'SocialTrading.API.exe', backup_file: 'SocialTrading.API.exe' }
        - { source_file: 'wwwadmin.zip', backup_file: 'wwwadmin.zip' }
        - { source_file: 'wwwuser.zip', backup_file: 'wwwuser.zip' }
        - { source_file: 'wwwwidgets.zip', backup_file: 'wwwwidgets.zip' } 

    - name: Copy Social Ratings files - Coping
      ansible.windows.win_copy:
        src: "{ ratings_path }\\{{ item.source_file }}"
        dest: "{ social_path }\\_backup\\{{ backup_file }}\\Ratings"
        remote_src: true
        when: Ratings_file_data.stat.exists
      loop:
        - { source_file: 'ijwhost.dll', backup_file: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', backup_file: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', backup_file: 'MNLog.config' }
        - { source_file: 'SocialTrading.Ratings.exe', backup_file: 'SocialTrading.Ratings.exe' }
        - { source_file: 'wwwcomponents.zip', backup_file: 'wwwcomponents.zip' }
        - { source_file: 'wwwroot.zip', backup_file: 'wwwroot.zip' }
        - { source_file: 'wwwwidgets.zip', backup_file: 'wwwwidgets.zip' }

    - name: Copy Social Worker files - Coping
      ansible.windows.win_copy:
        src: "{ worker_path }\\{{ item.source_file }}"
        dest: "{ social_path }\\_backup\\{{ backup_file }}\\Worker"
        remote_src: true
        when: worker_path is directory
      loop:
        - { source_file: 'ijwhost.dll', backup_file: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', backup_file: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', backup_file: 'MNLog.config' }
        - { source_file: 'SocialTrading.Worker.exe', backup_file: 'SocialTrading.Worker.exe' }  
