---
- name: PAMM Deploy
  hosts: windows
  gather_facts: false
  vars:
    # Application settings
    task_file: "{{ lookup('pipe','date +%Y-%m-%d') }} {{ semaphore_vars.task_details.id }}"
    services:
      - Core
      - Ratings
      - Worker

    # Variables on Task Start
    # download_link

    # Variables from Variable Groups:
    # app_path
    # app_service
    # mysql_db_name

    ## Database Variables
    # mysql_user
    # mysql_password
    # mysql_bin_path

  tasks:  
    - name: Create backup directories
      ansible.windows.win_file:
        path: "{{ app_path }}\\_backup\\{{ task_file }}\\{{ item.app_file }}"
        state: directory
      loop:
        - { app_file: "API" }
        - { app_file: "Ratings" }
        - { app_file: "Worker" }
        
    - name: Copy Social API
      ansible.windows.win_copy:
        src: "{{ app_path }}\\API\\{{ item.source_file }}"
        dest: "{{ app_path }}\\_backup\\{{ task_file }}\\API"
        remote_src: true
      loop:
        - { source_file: 'templates', date_var: '' }
        - { source_file: 'ijwhost.dll', date_var: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', date_var: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', date_var: 'MNLog.config' }
        - { source_file: 'SocialTrading.API.exe', date_var: 'SocialTrading.API.exe' }
        - { source_file: 'wwwadmin.zip', date_var: 'wwwadmin.zip' }
        - { source_file: 'wwwuser.zip', date_var: 'wwwuser.zip' }
        - { source_file: 'wwwwidgets.zip', date_var: 'wwwwidgets.zip' } 
        
    - name: Copy Social Ratings
      ansible.windows.win_copy:
        src: "{{ app_path }}\\Ratings\\{{ item.source_file }}"
        dest: "{{ app_path }}\\_backup\\{{ task_file }}\\Ratings"
        remote_src: true
      loop:
        - { source_file: 'ijwhost.dll', date_var: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', date_var: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', date_var: 'MNLog.config' }
        - { source_file: 'SocialTrading.Ratings.exe', date_var: 'SocialTrading.Ratings.exe' }
        - { source_file: 'wwwcomponents.zip', date_var: 'wwwcomponents.zip' }
        - { source_file: 'wwwroot.zip', date_var: 'wwwroot.zip' }
        - { source_file: 'wwwwidgets.zip', date_var: 'wwwwidgets.zip' }

    - name: Copy Social Worker
      ansible.windows.win_copy:
        src: "{{ app_path }}\\Worker\\{{ item.source_file }}"
        dest: "{{ app_path }}\\_backup\\{{ task_file }}\\Worker"
        remote_src: true
      loop:
        - { source_file: 'ijwhost.dll', date_var: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', date_var: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', date_var: 'MNLog.config' }

    - name: Stop Social Services
      ansible.windows.win_service:
        name: "{{ app_service }}.{{ item }}"
        state: stopped
        start_mode: manual
      loop: "{{ services }}"
      
    - name: Creating MySQL backup
      ansible.windows.win_powershell:
        script: |
          # Generate a back file name
          $backupFile = "{{ app_path }}\_backup\{{ task_file }}\{{ mysql_db_name }}_{{ task_file }}.sql"
          $backupFile2 = "{{ app_path }}\_backup\{{ task_file }}\{{ mysql_db_name }}_ratings_module_{{ task_file }}.sql"
          
          # Navigate to MySQL bin directory
          cd "{{ mysql_bin_path }}"
          
          # Execute mysqldump
          ./mysqldump.exe --user="{{ mysql_user }}" --password="{{ mysql_password }}" {{ mysql_db_name }} --result-file=$backupFile
          ./mysqldump.exe --user="{{ mysql_user }}" --password="{{ mysql_password }}" {{ mysql_db_name }}_ratings_module --result-file=$backupFile2
          
          # Verify file was created and isn't empty
          if (Test-Path $backupFile) {
              $size = (Get-Item $backupFile).Length
              return @{ backup_path = $backupFile; size_bytes = $size; success = $true }
          } else {
              throw "Mysqldump failed to create the backup file."
          }
      register: mysql_backup_result

    - name: Create update directory
      ansible.windows.win_file:
        path: "{{ app_path }}\\_update\\{{ task_file }}"
        state: directory

    - name: Download archive from Box
      ansible.windows.win_get_url:
        url: "{{ download_link }}"
        dest: "{{ app_path }}\\_update\\app.zip"

    - name: Unarchiving the artefacts
      community.windows.win_unzip:
        src: "{{ app_path }}\\_update\\app.zip"
        dest: "{{ app_path }}\\_update"
        rm: true

    - name: Update Social
      ansible.windows.win_copy:
        src: "{{ app_path }}\\_update\\Brokeree.SocialTrading\\{{ item.app_file }}\\"
        dest: "{{ app_path }}\\{{ item.app_file }}"
        remote_src: true
      loop:
        - { app_file: "API" }
        - { app_file: "Ratings" }
        - { app_file: "Worker" }
      
    - name: Starting PAMM Services
      ansible.windows.win_service:
        name: "{{ app_service }}.{{ item }}"
        state: started
        start_mode: delayed
      ignore_errors: true
      loop: "{{ services }}"

    - name: Deleting update folder
      ansible.windows.win_file:
        path: "{{ app_path }}\\_update"
        state: absent
