---
- name: Bridge Deploy
  hosts: windows
  gather_facts: false
  vars:
    # Application settings
    task_file: "{{ lookup('pipe','date +%Y-%m-%d') }} {{ semaphore_vars.task_details.id }}"
    services:
      - API
      - Core

    ## Variables on Task Start
    # box_link

    ## Variables from Variable Groups:    
    # app_path
    # app_service
    # mt_history_path
    # mt_history_service
    # mysql_user
    # mysql_password
    # mysql_db_name
    # mysql_bin_path
    
  tasks:    
    - name: Create backup directories
      ansible.windows.win_file:
        path: "{{ app_path }}\\_backup\\{{ task_file }}\\{{ item.bridge_file }}"
        state: directory
      loop:
        - { bridge_file: "Bridge.API" }
        - { bridge_file: "Bridge.Core" }
        - { bridge_file: "Gateway.MT5" }
        
    - name: Bridge.API Backup
      ansible.windows.win_copy:
        src: "{{ app_path }}\\PAMM\\{{ item.source_file }}"
        dest: "{{ app_path }}\\_backup\\{{ task_file }}\\PAMM"
        remote_src: true
      loop:
        - { source_file: 'OpenAPI', task_file: '' }
        - { source_file: 'wwwroot.zip', task_file: 'wwwroot.zip' }
        - { source_file: 'Bridge.API.exe', task_file: 'Bridge.API.exe' }
        - { source_file: 'Bridge.API.staticwebassets.endpoints.json', task_file: 'Bridge.API.staticwebassets.endpoints.json' }
        - { source_file: 'NLog.config', task_file: 'MNLog.config' }
        - { source_file: 'web.config', task_file: 'web.config' }
        
    - name: Bridge.Core Backup
      ansible.windows.win_copy:
        src: "{{ app_path }}\\PAMM.Ratings\\{{ item.source_file }}"
        dest: "{{ app_path }}\\_backup\\{{ task_file }}\\PAMM.Ratings"
        remote_src: true
      loop:
        - { source_file: 'Bridge.Core.exe', task_file: 'Bridge.Core.exe' }
        - { source_file: 'Bridge.Core.staticwebassets.endpoints.json', task_file: 'Bridge.Core.staticwebassets.endpoints.json' }
        - { source_file: 'DxFeedGraalNativeSdk.dll', task_file: 'DxFeedGraalNativeSdk.dll' }
        - { source_file: 'Epam.FixAntenna.Dialects.dll', task_file: 'Epam.FixAntenna.Dialects.dll' }
        - { source_file: 'Epam.FixAntenna.NetCore.dll', task_file: 'Epam.FixAntenna.NetCore.dll' }
        - { source_file: 'FIX44.xml', task_file: 'FIX44.xml' }
        - { source_file: 'fixengine.properties', task_file: 'fixengine.properties' }
        - { source_file: 'NLog.config', task_file: 'MNLog.config' }
        - { source_file: 'Providers.TestProvider.pdb', task_file: 'Providers.TestProvider.pdb' }
        - { source_file: 'web.config', task_file: 'web.config' }

    - name: Gateway.MT5 Backup
      ansible.windows.win_copy:
        src: "{{ mt_history_path }}\\Gateway\\Gateway.MT5\\{{ item.source_file }}"
        dest: "{{ app_path }}\\_backup\\{{ task_file }}\\Gateway.MT5"
        remote_src: true
      loop:
        - { source_file: 'Brokeree.Bridge.GW.MT5.exe', task_file: 'Brokeree.Bridge.GW.MT5.exe' }
        - { source_file: 'Brokeree.MT5GatewayAPI.Native.dll', task_file: 'Brokeree.MT5GatewayAPI.Native.dll' }
        - { source_file: 'Brokeree.MT5ManagerAPI.Native.dll', task_file: 'Brokeree.MT5ManagerAPI.Native.dll' }
        - { source_file: 'MT5APIGateway64.dll', task_file: 'MT5APIGateway64.dll' }
        - { source_file: 'MT5APIGateway64avx.dll', task_file: 'MT5APIGateway64avx.dll' }
        - { source_file: 'MT5APIGateway64avx2.dll', task_file: 'MT5APIGateway64avx2.dll' }
        - { source_file: 'MT5APIManager64.dll', task_file: 'MT5APIManager64.dll' }
        - { source_file: 'MT5APIManager64avx.dll', task_file: 'MT5APIManager64avx.dll' }
        - { source_file: 'MT5APIManager64avx2.dll', task_file: 'MT5APIManager64avx2.dll' }
        - { source_file: 'NLog.config', task_file: 'NLog.config' }

    - name: Stop Bridge Services
      ansible.windows.win_service:
        name: "{{ app_service }}.{{ item }}"
        state: stopped
        start_mode: manual
      loop: "{{ services }}"

    - name: Stop MT5 History Services
      ansible.windows.win_service:
        name: "{{ mt_history_service }}"
        state: stopped
        start_mode: manual    
      
    - name: Creating MySQL backup
      ansible.windows.win_powershell:
        script: |
          # Generate a back file name
          $backupFile = "{{ app_path }}\_backup\{{ task_file }}\{{ mysql_db_name }}_{{ task_file }}.sql"
          
          # Navigate to MySQL bin directory
          cd "{{ mysql_bin_path }}"
          
          # Execute mysqldump
          ./mysqldump.exe --user="{{ mysql_user }}" --password="{{ mysql_password }}" {{ mysql_db_name }} --result-file=$backupFile
          
          # Verify file was created and isn't empty
          if (Test-Path $backupFile) {
              $size = (Get-Item $backupFile).Length
              return @{ backup_path = $backupFile; size_bytes = $size; success = $true }
          } else {
              throw "Mysqldump failed to create the backup file."
          }
      register: mysql_backup_result

    - name: Create update directory
      ansible.windows.win_file:
        path: "{{ app_path }}\\_update\\{{ task_file }}"
        state: directory

    - name: Download artifacts from Box
      ansible.windows.win_get_url:
        url: "{{ box_link }}"
        dest: "{{ app_path }}\\_update\\{{ task_file }}\\Bridge.zip"

    - name: Unarchive artifacts
      community.windows.win_unzip:
        src: "{{ app_path }}\\_update\\{{ task_file }}\\Bridge.zip"
        dest: "{{ app_path }}\\_update\\{{ task_file }}"
        rm: true 

    - name: Update Bridge
      ansible.windows.win_copy:
        src: "{{ app_path }}\\_update\\{{ task_file }}\\{{ item.source_file }}"
        dest: "{{ app_path }}"
        remote_src: true
      loop:
        - { source_file: 'Bridge.API', task_file: '' }
        - { source_file: 'Bridge.Core', task_file: '' }

    - name: Update Gateway
      ansible.windows.win_copy:
        src: "{{ app_path }}\\_update\\{{ task_file }}\\Gateway.MT5"
        dest: "{{ mt_history_path }}\\Gateway"
        remote_src: true
        
    - name: Starting Bridge Services
      ansible.windows.win_service:
        name: "{{ app_service }}.{{ item }}"
        state: started
        start_mode: delayed
      ignore_errors: true
      loop: "{{ services }}"

    - name: Starting MT5 History Services
      ansible.windows.win_service:
        name: "{{ mt_history_service }}"
        state: started
        start_mode: delayed 
