---
- name: PAMM Deploy
  hosts: windows
  gather_facts: false
  vars:
    #Application settings
    backup_file: "{{ lookup('pipe','date +%Y-%m-%d') }}-{{ tc_build_id }}"
    services:
      - Core
      - Web
      - Ratings
    #TeamCity
    tc_server: "https://teamcity.brokeree.dev"
    tc_token: "eyJ0eXAiOiAiVENWMiJ9.bk9YX3RsWnVudS1GQjFxeU5KNFVyQm9tV1Js.NTdiZDRjY2UtNzkxNC00YzFjLWE3ODUtYWNlYTkzMTI2OTVh"
    
  tasks:
    - name: Create backup directories
      ansible.windows.win_file:
        path: "{{ pamm_path }}\\_backup\\{{ backup_file }}\\{{ item.pamm_file }}"
        state: directory
      loop:
        - { pamm_file: "PAMM" }
        - { pamm_file: "PAMM.Ratings" }
        - { pamm_file: "PAMM.Web" }
        
    - name: Copy PAMM Core
      ansible.windows.win_copy:
        src: "{{ pamm_path }}\\PAMM\\{{ item.source_file }}"
        dest: "{{ pamm_path }}\\_backup\\{{ backup_file }}\\PAMM"
        remote_src: true
      loop:
        - { source_file: 'ijwhost.dll', backup_file: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', backup_file: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', backup_file: 'MNLog.config' }
        - { source_file: 'PAMM.exe', backup_file: 'PAMM.exe' }
        
    - name: Copy PAMM Ratings
      ansible.windows.win_copy:
        src: "{{ pamm_path }}\\PAMM.Ratings\\{{ item.source_file }}"
        dest: "{{ pamm_path }}\\_backup\\{{ backup_file }}\\PAMM.Ratings"
        remote_src: true
      loop:
        - { source_file: 'ijwhost.dll', backup_file: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', backup_file: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', backup_file: 'MNLog.config' }
        - { source_file: 'PAMM.Ratings.exe', backup_file: 'PAMM.Ratings.exe' }
        - { source_file: 'wwwcomponents.zip', backup_file: 'wwwcomponents.zip' }
        - { source_file: 'wwwroot.zip', backup_file: 'wwwroot.zip' }
        - { source_file: 'wwwwidgets.zip', backup_file: 'wwwwidgets.zip' }

    - name: Copy PAMM Web
      ansible.windows.win_copy:
        src: "{{ pamm_path }}\\PAMM.Web\\{{ item.source_file }}"
        dest: "{{ pamm_path }}\\_backup\\{{ backup_file }}\\PAMM.Web"
        remote_src: true
      loop:
        - { source_file: 'templates', backup_file: '' }
        - { source_file: 'ijwhost.dll', backup_file: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', backup_file: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', backup_file: 'MNLog.config' }
        - { source_file: 'PAMM.API.xml', backup_file: 'PAMM.API.xml' }
        - { source_file: 'PAMM.Model.xml', backup_file: 'PAMM.Model.xml' }
        - { source_file: 'PAMM.Web.exe', backup_file: 'PAMM.Web.exe' }
        - { source_file: 'wwwadmin.zip', backup_file: 'wwwadmin.zip' }
        - { source_file: 'wwwinvestor.zip', backup_file: 'wwwinvestor.zip' }
        - { source_file: 'wwwmanager.zip', backup_file: 'wwwmanager.zip' } 

    - name: Stop PAMM Services
      ansible.windows.win_service:
        name: "{{ pamm_service }}.{{ item }}"
        state: stopped
        start_mode: manual
      loop: "{{ services }}"
      
    - name: Creating MySQL backup
      ansible.windows.win_powershell:
        script: |
          # Generate a back file name
          $backupFile = "{{ pamm_path }}\_backup\{{ backup_file }}\{{ mysql_db_name }}_{{ backup_file }}.sql"
          $backupFile2 = "{{ pamm_path }}\_backup\{{ backup_file }}\{{ mysql_db_name }}_ratings_module_{{ backup_file }}.sql"
          
          # Navigate to MySQL bin directory
          cd "{{ mysql_bin_path }}"
          
          # Execute mysqldump
          ./mysqldump.exe --user="{{ mysql_user }}" --password="{{ mysql_password }}" {{ mysql_db_name }} --result-file=$backupFile
          ./mysqldump.exe --user="{{ mysql_user }}" --password="{{ mysql_password }}" {{ mysql_db_name }}_ratings_module --result-file=$backupFile2
          
          # Verify file was created and isn't empty
          if (Test-Path $backupFile) {
              $size = (Get-Item $backupFile).Length
              return @{ backup_path = $backupFile; size_bytes = $size; success = $true }
          } else {
              throw "Mysqldump failed to create the backup file."
          }
      register: mysql_backup_result

    - name: Create update directory
      ansible.windows.win_file:
        path: "{{ pamm_path }}\\_update\\{{ backup_file }}"
        state: directory

    - name: Download artifacts from TeamCity
      ansible.windows.win_get_url:
        url: "{{ tc_server }}/repository/downloadAll/{{ tc_build_configuration_id }}/{{ tc_build_id }}:id"
        headers:
          Authorization: "Bearer {{ tc_token }}"
        dest: "{{ pamm_path }}\\_update\\{{ backup_file }}\\PAMM.zip"

    - name: Extract the artifact onto the Social directory
      community.windows.win_unzip:
        src: "{{ pamm_path }}\\_update\\{{ backup_file }}\\PAMM.zip"
        dest: "{{ pamm_path }}"
        rm: true 
      
    - name: Starting Social Services
      ansible.windows.win_service:
        name: "{{ pamm_service }}.{{ item }}"
        state: started
        start_mode: delayed
      loop: "{{ services }}"
