---
- name: PAMM Deploy
  hosts: windows
  gather_facts: false
  vars:
    # Application settings
    task_file: "{{ lookup('pipe','date +%Y-%m-%d') }} {{ semaphore_vars.task_details.id }}"
    app_name: "Brokeree.PAMM"
    services:
      - Core
      - Web
      - Ratings

    ## Variables on Task Start
    # tc_version
    # tc_build_configuration_id
    # tc_build_branch
    # tc_build_id

    ## Variables from Variable Groups:
    # app_path
    # app_service
    # mysql_db_name

    # mysql_user
    # mysql_password
    # mysql_bin_path

    # tc_server  
    # tc_token

  tasks:
    - name: Build details
      ansible.builtin.debug:
        msg:
          - "{{ tc_version }}"
          - "{{ tc_build_configuration_id }}"
          - "{{ tc_build_branch }}"
          - "{{ tc_build_id }}"
    
    - name: Create backup directories
      ansible.windows.win_file:
        path: "{{ app_path }}\\_backup\\{{ task_file }}\\{{ item.app_file }}"
        state: directory
      loop:
        - { app_file: "PAMM" }
        - { app_file: "PAMM.Ratings" }
        - { app_file: "PAMM.Web" }
        
    - name: Copy PAMM Core
      ansible.windows.win_copy:
        src: "{{ app_path }}\\PAMM\\{{ item.source_file }}"
        dest: "{{ app_path }}\\_backup\\{{ task_file }}\\PAMM"
        remote_src: true
      loop:
        - { source_file: 'ijwhost.dll', task_file: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', task_file: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', task_file: 'MNLog.config' }
        - { source_file: 'PAMM.exe', task_file: 'PAMM.exe' }
        
    - name: Copy PAMM Ratings
      ansible.windows.win_copy:
        src: "{{ app_path }}\\PAMM.Ratings\\{{ item.source_file }}"
        dest: "{{ app_path }}\\_backup\\{{ task_file }}\\PAMM.Ratings"
        remote_src: true
      loop:
        - { source_file: 'ijwhost.dll', task_file: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', task_file: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', task_file: 'MNLog.config' }
        - { source_file: 'PAMM.Ratings.exe', task_file: 'PAMM.Ratings.exe' }
        - { source_file: 'wwwcomponents.zip', task_file: 'wwwcomponents.zip' }
        - { source_file: 'wwwroot.zip', task_file: 'wwwroot.zip' }
        - { source_file: 'wwwwidgets.zip', task_file: 'wwwwidgets.zip' }

    - name: Copy PAMM Web
      ansible.windows.win_copy:
        src: "{{ app_path }}\\PAMM.Web\\{{ item.source_file }}"
        dest: "{{ app_path }}\\_backup\\{{ task_file }}\\PAMM.Web"
        remote_src: true
      loop:
        - { source_file: 'templates', task_file: '' }
        - { source_file: 'ijwhost.dll', task_file: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', task_file: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', task_file: 'MNLog.config' }
        - { source_file: 'PAMM.API.xml', task_file: 'PAMM.API.xml' }
        - { source_file: 'PAMM.Model.xml', task_file: 'PAMM.Model.xml' }
        - { source_file: 'PAMM.Web.exe', task_file: 'PAMM.Web.exe' }
        - { source_file: 'wwwadmin.zip', task_file: 'wwwadmin.zip' }
        - { source_file: 'wwwinvestor.zip', task_file: 'wwwinvestor.zip' }
        - { source_file: 'wwwmanager.zip', task_file: 'wwwmanager.zip' } 

    - name: Stop PAMM Services
      ansible.windows.win_service:
        name: "{{ app_service }}.{{ item }}"
        state: stopped
        start_mode: manual
      loop: "{{ services }}"
      
    - name: Creating MySQL backup
      ansible.windows.win_powershell:
        script: |
          # Generate a back file name
          $backupFile = "{{ app_path }}\_backup\{{ task_file }}\{{ mysql_db_name }}_{{ task_file }}.sql"
          $backupFile2 = "{{ app_path }}\_backup\{{ task_file }}\{{ mysql_db_name }}_ratings_module_{{ task_file }}.sql"
          
          # Navigate to MySQL bin directory
          cd "{{ mysql_bin_path }}"
          
          # Execute mysqldump
          ./mysqldump.exe --user="{{ mysql_user }}" --password="{{ mysql_password }}" {{ mysql_db_name }} --result-file=$backupFile
          ./mysqldump.exe --user="{{ mysql_user }}" --password="{{ mysql_password }}" {{ mysql_db_name }}_ratings_module --result-file=$backupFile2
          
          # Verify file was created and isn't empty
          if (Test-Path $backupFile) {
              $size = (Get-Item $backupFile).Length
              return @{ backup_path = $backupFile; size_bytes = $size; success = $true }
          } else {
              throw "Mysqldump failed to create the backup file."
          }
      register: mysql_backup_result

    - name: Create update directory
      ansible.windows.win_file:
        path: "{{ app_path }}\\_update"
        state: directory

    - name: Download artifacts from TeamCity
      ansible.windows.win_get_url:
        url: "{{ tc_server }}/repository/download/{{ tc_build_configuration_id }}/{{ tc_build_id }}:id/{{ app_name }}-{{ tc_version | urlencode }}.zip"
        headers:
          Authorization: "Bearer {{ tc_token }}"
        dest: "{{ app_path }}\\_update\\app.zip"

    - name: Unarchiving the artefacts
      community.windows.win_unzip:
        src: "{{ app_path }}\\_update\\app.zip"
        dest: "{{ app_path }}\\_update"
        rm: true

    - name: Update PAMM
      ansible.windows.win_copy:
        src: "{{ app_path }}\\_update\\{{ app_name }}\\{{ item.app_file }}\\"
        dest: "{{ app_path }}\\{{ item.app_file }}"
        remote_src: true
      loop:
        - { app_file: "PAMM" }
        - { app_file: "PAMM.Web" }
        - { app_file: "PAMM.Ratings" }
      
    - name: Starting PAMM Services
      ansible.windows.win_service:
        name: "{{ app_service }}.{{ item }}"
        state: started
        start_mode: delayed
      ignore_errors: true
      loop: "{{ services }}"

    - name: Deleting update folder
      ansible.windows.win_file:
        path: "{{ app_path }}\\_update"
        state: absent
