---
- name: testing
  hosts: windows
  gather_facts: false
  vars:
    test_path: "C:\\Tests"
    
  tasks:
    - name: Dump available task details
      ansible.builtin.debug:
        var: semaphore_vars.task_details
        
    - name: Create directories
      ansible.windows.win_file:
        path: "{{ test_path }}\\test01-{{ name_dir }}"
        state: directory

    - name: Inspect target Semaphore URL
      ansible.builtin.debug:
        msg: "Targeting URL: https://semaphore.brokeree.dev/api/project/1/tasks/{{ semaphore_vars.task_details.id }}"
