---
- name: Social Backup
  hosts: windows
  gather_facts: false
  vars:
    # Social Configuration
    date_var: "{{ lookup('pipe','date +%Y-%m-%d') }}"
    # Social Services
    services:
      - {{ social_service }}.API
      - {{ social_service }}.Ratings
    #  - Brokeree.Social.Worker
    #TeamCity
#    target_branch: "support/5.x"
    tc_server: "https://teamcity.brokeree.dev"
    tc_build_type_id: "SocialPlatform_Build"
    tc_token: "eyJ0eXAiOiAiVENWMiJ9.bk9YX3RsWnVudS1GQjFxeU5KNFVyQm9tV1Js.NTdiZDRjY2UtNzkxNC00YzFjLWE3ODUtYWNlYTkzMTI2OTVh"
    
  tasks:
    - name: Create backup directories
      ansible.windows.win_file:
        path: "{{ social_path }}\\_backup\\{{ date_var }}\\{{ item.social_file }}"
        state: directory
      loop:
        - { social_file: "API" }
        - { social_file: "Ratings" }
        - { social_file: "Worker" }
        
    - name: Copy Social API files
      ansible.windows.win_copy:
        src: "{{ social_path }}\\API\\{{ item.source_file }}"
        dest: "{{ social_path }}\\_backup\\{{ date_var }}\\API"
        remote_src: true
      loop:
        - { source_file: 'templates', date_var: '' }
        - { source_file: 'ijwhost.dll', date_var: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', date_var: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', date_var: 'MNLog.config' }
        - { source_file: 'SocialTrading.API.exe', date_var: 'SocialTrading.API.exe' }
        - { source_file: 'wwwadmin.zip', date_var: 'wwwadmin.zip' }
        - { source_file: 'wwwuser.zip', date_var: 'wwwuser.zip' }
        - { source_file: 'wwwwidgets.zip', date_var: 'wwwwidgets.zip' } 
        
    - name: Copy Social Ratings files
      ansible.windows.win_copy:
        src: "{{ social_path }}\\Ratings\\{{ item.source_file }}"
        dest: "{{ social_path }}\\_backup\\{{ date_var }}\\Ratings"
        remote_src: true
      loop:
        - { source_file: 'ijwhost.dll', date_var: 'ijwhost.dll' }
        - { source_file: 'MT5APIManager64.dll', date_var: 'MT5APIManager64.dll' }
        - { source_file: 'NLog.config', date_var: 'MNLog.config' }
        - { source_file: 'SocialTrading.Ratings.exe', date_var: 'SocialTrading.Ratings.exe' }
        - { source_file: 'wwwcomponents.zip', date_var: 'wwwcomponents.zip' }
        - { source_file: 'wwwroot.zip', date_var: 'wwwroot.zip' }
        - { source_file: 'wwwwidgets.zip', date_var: 'wwwwidgets.zip' }

#    - name: Copy Social Worker files
#      ansible.windows.win_copy:
#        src: "{{ social_path }}\\Worker\\{{ item.source_file }}"
#        dest: "{{ social_path }}\\_backup\\{{ date_var }}\\Worker"
#        remote_src: true
#      loop:
#        - { source_file: 'ijwhost.dll', date_var: 'ijwhost.dll' }
#        - { source_file: 'MT5APIManager64.dll', date_var: 'MT5APIManager64.dll' }
#        - { source_file: 'NLog.config', date_var: 'MNLog.config' }

    - name: Stop Social Services
      ansible.windows.win_service:
        name: "{{ social_service }}.API"
        state: stopped
        start_mode: manual
      ansible.windows.win_service:
        name: "{{ social_service }}.Ratings"
        state: stopped
        start_mode: manual
      
    - name: Creating MySQL backup
      ansible.windows.win_powershell:
        script: |
          # Generate a back file name
          $backupFile = "{{ social_path }}\_backup\{{ date_var }}\{{ mysql_db_name }}_{{ date_var }}.sql"
          
          # Navigate to MySQL bin directory
          cd "{{ mysql_bin_path }}"
          
          # Execute mysqldump
          ./mysqldump.exe --user="{{ mysql_user }}" --password="{{ mysql_password }}" {{ mysql_db_name }} --result-file=$backupFile
          
          # Verify file was created and isn't empty
          if (Test-Path $backupFile) {
              $size = (Get-Item $backupFile).Length
              return @{ backup_path = $backupFile; size_bytes = $size; success = $true }
          } else {
              throw "Mysqldump failed to create the backup file."
          }
      register: mysql_backup_result

    - name: Create update directories
      ansible.windows.win_file:
        path: "{{ social_path }}\\_update\\{{ date_var }}"
        state: directory

    - name: Query TeamCity for the build ID
      ansible.builtin.uri:
        url: "{{ tc_server }}/app/rest/builds?locator=buildType:{{ tc_build_type_id }},branch:{{ target_branch }},status:SUCCESS,count:1"
        method: GET
        headers:
          Accept: "application/json"
          Authorization: "Bearer {{ tc_token }}"
        status_code: 200
      register: tc_build_response
      delegate_to: localhost

    - name: Fail if no successful builds are found
      ansible.builtin.fail:
        msg: "No successful builds found for branch '{{ target_branch }}'."
      when: tc_build_response.json.count == 0
      delegate_to: localhost

    - name: Extract the Build ID
      ansible.builtin.set_fact:
        latest_build_id: "{{ tc_build_response.json.build[0].id }}"
      delegate_to: localhost

    - name: Download artifacts from TeamCity
      ansible.windows.win_get_url:
        url: "{{ tc_server }}/repository/downloadAll/{{ tc_build_type_id }}/{{ latest_build_id }}:id"
        headers:
          Authorization: "Bearer {{ tc_token }}"
        dest: "{{ social_path }}\\_update\\{{ date_var }}\\ST.zip"

    - name: Extract the artifact onto the Social directory
      community.windows.win_unzip:
        src: "{{ social_path }}\\_update\\{{ date_var }}\\ST.zip"
        dest: "{{ social_path  }}"
        rm: true 
      
    - name: Starting Social Services
      ansible.windows.win_service:
        name: "{{ item }}"
        state: started
        start_mode: delayed
      loop: "{{ services }}"
