---
- name: PAMM Deploy
  hosts: windows
  gather_facts: false
  vars:
    test_path: "C:\\Tests"
    
  tasks:
    - name: Create backup directories
      ansible.windows.win_file:
        path: "{{ test_path }}\\test02"
        state: directory
