---
- name: Social Backup
  hosts: windows
  gather_facts: false
  vars:
    # Social Configuration
    date: "{{ lookup('pipe','date +%Y-%m-%d') }}"
    social_path: 'C:\Brokeree\Brokeree.Social'
    social_path2: 'C:\Brokeree\Brokeree.Social-2'
    # MySQL Configuration
    mysql_user: "Admin"
    mysql_password: "BrokereeAdmin"
    mysql_db_name: "social_trading"
    mysql_bin_path: 'C:\Program Files\MySQL\MySQL Server 8.4\bin'
    # Social Services
    services:
      - Brokeree.Social.API
      - Brokeree.Social.Ratings
    #  - Brokeree.Social.Worker
    #TeamCity
    target_branch: "support/5.x"
    tc_server: "https://teamcity.brokeree.dev"
    tc_build_type_id: "SocialPlatform_Build"
    tc_token: "eyJ0eXAiOiAiVENWMiJ9.bk9YX3RsWnVudS1GQjFxeU5KNFVyQm9tV1Js.NTdiZDRjY2UtNzkxNC00YzFjLWE3ODUtYWNlYTkzMTI2OTVh"
    
  tasks:
    - name: Query TeamCity for the build ID
      ansible.builtin.uri:
        url: "{{ tc_server }}/app/rest/builds?locator=buildType:{{ tc_build_type_id }},branch:{{ target_branch }},status:SUCCESS,count:1"
        method: GET
        headers:
          Accept: "application/json"
          Authorization: "Bearer {{ tc_token }}"
        status_code: 200
      register: tc_build_response
      delegate_to: localhost

    - name: Fail if no successful builds are found
      ansible.builtin.fail:
        msg: "No successful builds found for branch '{{ target_branch }}'."
      when: tc_build_response.json.count == 0
      delegate_to: localhost

    - name: Extract the Build ID
      ansible.builtin.set_fact:
        latest_build_id: "{{ tc_build_response.json.build[0].id }}"
      delegate_to: localhost

    - name: Create update directories
      ansible.windows.win_file:
        path: "{{ social_path }}\\_update\\{{ date }}"
        state: directory

    - name: Download artifacts from TeamCity
      ansible.windows.win_get_url:
        url: "{{ tc_server }}/repository/downloadALL/{{ tc_build_type_id }}/{{ latest_build_id }}:id"
        url_username: "oauth2"
        url_password: "{{ tc_token }}"
        dest: "{{ social_path }}\\_update\\{{ date }}"

    - name: Extract the artifact onto the Windows Server
      community.windows.win_unzip:
        src: "{{ social_path }}\\_update\\{{ date }}"
        dest: "{{ social_path2  }}"
        rm: true 
